---
title: "MSBA Workshop: Calculus --- A Few Things about Integrals"
format:
  html:
    embed-resources: true
---

In each of the following situations, we want to compute the distance traveled by a person walking for 60 seconds.
In each part:

-   Sketch a plot of speed versus time.
-   How is total distance traveled represented in this plot?
-   Compute the total distance traveled over 60 seconds.

1.  The person walks at a constant speed of 3 m/s for 60 seconds.
<div style="height: 4cm;"></div>

2.  The person walks at a constant speed of 3 m/s for the first 20 seconds and 5 m/s for the next 40 seconds. 
<div style="height: 4cm;"></div>

3.  Their speed at $t$ seconds is $0.1t$.
<div style="height: 4cm;"></div>

4.  Their speed at $t$ seconds is given by
$$
f(t) = 
\begin{cases}
0.2t, & 0<t<20,\\
4, & 20 < t < 40,\\
12-0.2t, & 40<t<60
\end{cases}
$$

<div style="height: 4cm;"></div>

5.  Suppose their speed at $t$ seconds is given by $400(t/60)^5(1-t/60)^2$.
How could you *approximate* the total distance traveled?
How could you get a better approximation?
<div style="height: 4cm;"></div>


## Integral

-   An integral is commonly interpreted as an [area under a curve](https://www.google.com/search?sca_esv=b510d2a75869389b&rlz=1C1GCEA_enUS1148US1148&sxsrf=AE3TifOiQiJ7QcRUDyU5QrhVlEBUeQmH5g:1755103094426&udm=2&fbs=AIIjpHxU7SXXniUZfeShr2fp4giZ1Y6MJ25_tmWITc7uy4KIeoJTKjrFjVxydQWqI2NcOha3O1YqG67F0QIhAOFN_ob1yXos5K_Qo9Tq-0cVPzex8akBC0YDCZ6Kdb3tXvKc6RFFaJZ5G23Reu3aSyxvn2qD41n-47oj-b-f0NcRPP5lz0IcnVzj2DIj_DMpoDz5XbfZAMcEl5-58jjbkgCC_7e4L5AEDQ&q=integral+as+area+under+the+curve&sa=X&ved=2ahUKEwjo-vLDnIiPAxWPFjQIHV4CABsQtKgLegQIERAB&biw=1920&bih=945&dpr=1)

$$
\int_a^b f(x) dx = \text{Area under curve $f$ over the interval $[a, b]$}
$$

-   You can [approximate an integral](https://en.wikipedia.org/wiki/Riemann_sum#Connection_with_integration) $\int_a^b f(x) dx$> by chopping the interval $[a, b]$ into many small intervals, and approximating the area under the curve with the sum of the areas of many narrow rectangles with heights specified by $f$.

-   [Fundamental theorem of calculus](https://www.youtube.com/watch?v=rfG8ce4nNh0): If $F$ is a function whose derivative is $f$, that is $\frac{d}{dx} F(x) = f(x)$ then

$$
\int_a^b f(x)dx = F(b) - F(a)
$$


## Integration in Python

```{python}
from sympy import integrate, Symbol

# Define the variable
t = Symbol('t')

# Define the function to integrate
ft = 0.1 * t

# Calculate the integral of 0.1t from 0 to 60
integrate(ft, (t, 0, 60))

```

```{python}
t = Symbol('t')

ft = 400 *(t / 60)**5 * (1 - t / 60)**2

integrate(ft, (t, 0, 60))
```


## Online integration tools

-   [WolframAlpha](https://www.wolframalpha.com/calculators/integral-calculator?src=google&388=&gad_source=1&gad_campaignid=6479022389&gbraid=0AAAAAD032FmLiBFsBcYGNkroOhP5SJLlQ&gclid=Cj0KCQjwqebEBhD9ARIsAFZMbfwQ47v7QiJUcPv3oii4IQLTcsHpnP04H7O2j92dzwMu7jiUSjfk_90aAn08EALw_wcB)
-   [Symbolab](https://www.symbolab.com/solver/integral-calculator)
-   [Desmos](https://www.desmos.com/calculator/zv8ghd2hsj)

