---
title: "MSBA Math & Coding Workshop"
author: "Kevin Ross, Statistics"
format:
  revealjs: 
    theme: dracula
    embed-resources: true
---


## Goal: Brief Refresher/Baseline Exposure

:::: {.columns}

::: {.column width="50%"}
### Day 1 (Coding)
 - Python
 - Data wrangling and visualization
 - Juypter/Colab
 - Quarto
 - Positron
 - Git/GitHub
:::

::: {.column width="50%"}
### Day 2 (Math)
 - Logarithms
 - Calculus: Integrals
 - Calculus: Derivatives
 - Statistics (mostly regression)
 - Matrix algebra
:::

::::


## Expectations

- Just the very basics
- You should ask lots of questions...
  - But I might not answer some questions (to keep to the very basics)
  - But should also be time for individual conversations
- Workshop is optional but if you're here I expect you to participate
- [Work together! Help each other!](https://forms.office.com/Pages/AnalysisPage.aspx?AnalyzerToken=KvZNjUgAVGKoSiMvThCZxnFo90uS9xFt&id=2wING578lUSVNx03nMoq5zdy3BzI595OigysnO88k99UMDBQU09MSURGS1laSk9WMjRTSzgyUUo1OC4u)
- [Zoom check in times](https://calpoly.zoom.us/j/7097363326) at 11:00, 12:00, 2:00, 2:45; about 10 minutes each


## Day 1 Morning: Using Colab for Data Science

1.  Create a [Google account](https://www.google.com/intl/en-GB/account/about/)
1.  [Intro to Colab](https://colab.research.google.com/drive/1qaTWpyJmOHlc-ZFy0atBUuuQi84d2Ly5?usp=sharing)
1.  [Intro to Python](https://colab.research.google.com/drive/1xE_nzRruCpovQM_O5_-gXxkF_Hv_HfgC?usp=sharing)
1.  [Intro to Pandas](https://colab.research.google.com/drive/1rwzQfrHZ67Sn5njKe1Bf4QpEI0HeblSL?usp=sharing)
1.  [Intro to data visualization with Python](https://colab.research.google.com/drive/1L_F4X-W_naa-mWoeogyTbOrPHh5TYYu2?usp=sharing)



## Colab is great, but...

- Limited amount of free compute time offered by Google
- Not much flexibility or control over the documents
- Limited ability to customize workspace
  - What if you want to see your text, your code, your plots, your data, your variables, etc, and have tools for debugging, report creation, etc
- Not great for larger projects or data sets
- Not great for production quality reports and presentations
- Not a great workspace for a professional data scientist



## Day 2 Afternoon: Setting up your Workspace


1.  Install programs (hopefully!):
    -   [Anaconda](https://www.anaconda.com/download)
    -   [Quarto](https://quarto.org/docs/get-started/)
    -   [Positron](https://positron.posit.co/start.html)
    -   [Git](https://git-scm.com/)
1.  Intro to Quarto documents and Positron
1.  Version control/collaboration and Git/Github





## Version control/collaboration and Git/GitHub

- You are probably familiar with tools like "track changes" or shared Google docs
- Colab has similar features
- Git/GitHub enables version control/collaboration on a much larger scale
- Create a [GitHub account](https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github)
- Try the [GitHub tutorial](https://docs.github.com/en/get-started/start-your-journey/hello-world)
- Watch this [video](https://www.youtube.com/watch?v=BCQHnlnPusY)



## Activity: From Colab to GitHub

- Take a notebook you used in Colab, keep working on it locally, and share it like a real project
- Follow along: `msba-workshop-activity-colab-to-github.qmd`
  1. Download a Colab notebook as `.ipynb`
  2. Open and edit it in Positron
  3. Render it to HTML with Quarto (`quarto render`)
  4. Create a GitHub repository
  5. Upload both the `.ipynb` and `.html` files


## Day 2 Morning: Just a Little Calculus

- Basics of Logarithms
- Calculus: Derivatives
- Calculus: Integrals


## Day 2 Afternoon: Just a Little Statistics and Matrix Algebra

- World Cup
- Regression
- Matrix algebra


## OMG I have to learn/remember all this stuff

::: {.incremental}
- BUT
- Usually just very fundamental things
- Seeing it now, still have time to brush up before you really need it in courses
- Rely on software to compute; focus on concepts
- Work together!!! Help each other!!!
:::
